version: 2

project_name: warpdl

release:
  github:
    owner: warpdl
    name: warpdl
  replace_existing_draft: true
  header: |
    ## Installation

    **macOS (Homebrew):**
    ```bash
    brew tap warpdl/tap && brew install warpdl
    ```

    **Windows (Scoop):**
    ```powershell
    scoop bucket add warpdl https://github.com/warpdl/scoop-bucket
    scoop install warpdl
    ```

    **Linux/macOS/BSD (Direct install):**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/warpdl/warpdl/dev/scripts/install.sh | sh
    ```

    **Docker:**
    ```bash
    docker pull ghcr.io/warpdl/warp-cli:{{ .Tag }}
    ```

gomod:
  env:
    - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy
    - go mod download

# upx:
#   - enabled: true
#     brute: true

builds:
  - id: default
    binary: warpdl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: "386"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.buildType=stable
  - id: android
    binary: warpdl
    env:
      - CGO_ENABLED=0
    goos:
      - android
    goarch:
      - arm64
    goarm:
      - "6"
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.buildType=stable

archives:
  - id: default
    ids:
      - default
      - android
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    
signs:
  - artifacts: all
    args:
      - "-u"
      - "C4223C5D4162629F38AF4DD530695AF88CC00E38"
      - "--output"
      - "${signature}"
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "$GPG_PASSPHRASE"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

brews:
  - name: warpdl
    repository:
      owner: warpdl
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: "Divkix"
      email: divkix@divkix.me
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/warpdl/warpdl"
    description: "The official Warp CLI download manager"
    license: "MIT"
    install: |
      bin.install "warpdl"
    post_install: |
      # Stop any running daemon from a previous version to ensure clean upgrade
      begin
        system "#{bin}/warpdl", "stop-daemon"
      rescue
        # Daemon wasn't running, that's fine
      end
    caveats: |
      The WarpDL daemon runs in the background to manage downloads.

      Before uninstalling, stop the daemon with:
        warpdl stop-daemon

      The daemon auto-starts when needed. No manual startup required.
    custom_block: |
      def pre_uninstall
        begin
          system bin/"warpdl", "stop-daemon"
        rescue
          # Daemon may not be running
        end
      end
    test: |
      system "#{bin}/warpdl", "--version"

scoops:
  - name: warpdl
    repository:
      owner: warpdl
      name: scoop-bucket
    commit_author:
      name: "Divkix"
      email: divkix@divkix.me
    homepage: "https://github.com/warpdl/warpdl"
    description: "The official Warp CLI download manager"

nfpms:
  - id: default
    package_name: warpdl
    vendor: WarpDL
    homepage: https://github.com/warpdl/warpdl
    maintainer: Divkix <divkix@divkix.me>
    description: WarpDL - High-performance parallel download manager with daemon architecture
    license: MIT
    builds:
      - default
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/local/bin
    section: utils
    priority: optional
    rpm:
      group: Applications/Internet
    file_name_template: >-
      {{ .PackageName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}armhf
      {{- else }}{{ .Arch }}{{ end }}
    contents:
      - src: scripts/warpdl.service
        dst: /usr/lib/systemd/user/warpdl.service
        type: config|noreplace
        file_info:
          mode: 0644
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh
    overrides:
      deb:
        dependencies:
          - systemd
      rpm:
        dependencies:
          - systemd
      apk: {}

dockers_v2:
  - id: warp-cli
    dockerfile: docker/goreleaser
    images:
      - "ghcr.io/warpdl/warp-cli"
    tags:
      - "{{ .Tag }}"
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "warp-cli"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
