project_name: warp
release:
  replace_existing_draft: true
  header: |
    Welcome to this new release!
before:
  hooks:
    - go mod tidy
    - go mod download
gomod:
  env:
    - GOPRIVATE=github.com/warpdl/warplib
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
