# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: warpdl

release:
  github:
    owner: warpdl
    name: warp-releases
  replace_existing_draft: true
  header: |
    Welcome to this new release!

    Docker 🐳 images are available at:
    `docker pull ghcr.io/warpdl/warp-cli:{{ .Tag }}`

gomod:
  env:
    - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy
    - go mod download

# upx:
#   - enabled: true
#     brute: true

builds:
  - binary: warpdl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: freebsd
        goarch: "386"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.BuildType=stable

archives:
  # - rlcp: true
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

signs:
  - artifacts: all
    args:
      - "-u"
      - "C4223C5D4162629F38AF4DD530695AF88CC00E38"
      - "--output"
      - "${signature}"
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "$GPG_PASSPHRASE"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - name: warpdl
    repository:
      owner: warpdl
      name: homebrew-tap
    commit_author:
      name: "Divkix"
      email: divkix@divkix.me
    directory: Formula
    homepage: "https://warpdl.org"
    description: "The official Warp CLI download manager"
    install: |-
      bin.install "warpdl"
    test: |
      system "#{bin}/warpdl --version"

scoops:
  - name: warpdl
    repository:
      owner: warpdl
      name: scoop-bucket
    commit_author:
      name: "Divkix"
      email: divkix@divkix.me
    homepage: "https://warpdl.org"
    description: "The official Warp CLI download manager"

nfpms:
  - file_name_template: >-
      {{ .PackageName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    homepage: "https://warpdl.org"
    maintainer: Divanshu Chauhan <divkix@divkix.me>
    description: "The official Warp CLI download manager"
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - apk

# snapcrafts:
#   - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#     publish: false
#     summary: An ultra fast download manager
#     description: |-
#       Warp is a powerful and versatile cross-platform download manager.
#       With its advanced technology, Warp has the ability to accelerate
#       your download speeds by up to 10 times, revolutionizing the way
#       you obtain files on any operating system.
#     grade: stable
#     confinement: strict
#     base: core18
#     apps:
#       warpdl:
#         command: usr/bin/warpdl

dockers:
  - goarch: amd64
    dockerfile: docker/goreleaser
    use: buildx
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=warp-cli"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goarch: arm64
    dockerfile: docker/goreleaser
    use: buildx
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=warp-cli"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/warpdl/warp-cli:{{ .Version }}"
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-amd64"
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-arm64v8"
  - name_template: "ghcr.io/warpdl/warp-cli:latest"
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-amd64"
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-arm64v8"
