//go:build ignore

package main

import (
    "fmt"
    "os"
    "path/filepath"
    "regexp"
    "strings"

    "github.com/warpdl/warpdl/cmd"
)

const frontmatter = `---
title: CLI Reference
description: Complete command-line reference for WarpDL
---

{/* AUTO-GENERATED FILE - DO NOT EDIT MANUALLY */}
{/* Generated by docs/scripts/generate-cli-docs.go */}

`

// escapeAngleBrackets escapes < and > outside of code blocks to prevent MDX/JSX interpretation
func escapeAngleBrackets(md string) string {
    // Match angle brackets that look like placeholders (e.g., <command>, <url>)
    // but not inside code blocks (``` ... ```) or inline code (` ... `)
    re := regexp.MustCompile(`<(\w+)>`)
    return re.ReplaceAllString(md, "`<$1>`")
}

// cleanManPageFormat removes man page style formatting from ToMarkdown() output
func cleanManPageFormat(md string) string {
    // Remove % warpdl(8) header and description block
    re1 := regexp.MustCompile(`(?s)% warpdl\(\d+\).*?\n\n+%\s*\n+`)
    md = re1.ReplaceAllString(md, "")

    // Remove any remaining standalone % lines
    re2 := regexp.MustCompile(`(?m)^%\s*$\n?`)
    md = re2.ReplaceAllString(md, "")

    return md
}

// toTitleCase converts "GLOBAL OPTIONS" to "Global Options"
func toTitleCase(s string) string {
    words := strings.Fields(strings.ToLower(s))
    for i, w := range words {
        if len(w) > 0 {
            words[i] = strings.ToUpper(w[:1]) + w[1:]
        }
    }
    return strings.Join(words, " ")
}

// convertH1ToH2 converts man page H1 headers to H2 with title case
// e.g., "# GLOBAL OPTIONS" → "## Global Options"
func convertH1ToH2(md string) string {
    re := regexp.MustCompile(`(?m)^# ([A-Z][A-Z ]+)$`)
    return re.ReplaceAllStringFunc(md, func(match string) string {
        // Extract the header text (remove "# ")
        header := strings.TrimPrefix(match, "# ")
        return "## " + toTitleCase(header)
    })
}

func main() {
    app := cmd.GetApp(cmd.BuildArgs{Version: "latest"})

    md, err := app.ToMarkdown()
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error generating markdown: %v\n", err)
        os.Exit(1)
    }

    // Clean up man page style formatting
    md = cleanManPageFormat(md)

    // Convert H1 caps headers to H2 title case (for TOC visibility)
    md = convertH1ToH2(md)

    // Escape angle brackets to prevent MDX/JSX interpretation
    md = escapeAngleBrackets(md)

    content := frontmatter + md

    outPath := filepath.Join("docs", "src", "content", "docs", "usage", "cli-reference.mdx")

    if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
        fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
        os.Exit(1)
    }

    fmt.Printf("Generated %s\n", outPath)
}
