name: warpdl 
base: core18
version: '1.0.4'
summary: An ultra fast download manager
description: |
  Warp is a powerful and versatile cross-platform download manager. 
  With its advanced technology, Warp has the ability to accelerate
  your download speeds by up to 10 times, revolutionizing the way
  you obtain files on any operating system.


grade: stable 
confinement: strict

parts:
  warpdl:
    plugin: dump
    source-type: deb
    source: https://github.com/warpdl/warp-releases/releases/download/$SNAPCRAFT_PROJECT_VERSION/warpdl_$SNAPCRAFT_PROJECT_VERSION_linux_$SNAPCRAFT_TARGET_ARCH.deb
  
apps:
  warpdl:
    command: usr/bin/warpdl
    plugs:
      - home
      - network
      - network-bind
